### ISSUE TITLE
Use await instead of manually waiting

### ISSUE THREAD

**Issue by nabijaczleweli** [nabijaczleweli/checksums#13]
Implemented here: https://github.com/alexcrichton/futures-rs/pull/20, but not released

**Comment by Dr-Emann** [comment]
Since futures-rs is still under pretty heavy development, to the point of suggesting using a git dependency, what are your thoughts on moving to a more established threadpool crate (maybe [`threadpool`](https://crates.io/crates/threadpool)?). Unfortunately no threadpools I've found return a future-like object, which can be waited on and returns a value, but it could be emulated by using a channel, and sending hashes through a `Sender<(String, String)>`, and using `Reciver::iter()` to loop over the values returned.

**Comment by nabijaczleweli** [comment]
Nah, waiting for `wait` ain't gonna be too long, let's stick with `futures` since it provides everything we need and new version should not be not too long away (see https://github.com/alexcrichton/futures-rs/pull/20#issuecomment-242479780)
